//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademyEntities : DbContext
    {
        public AcademyEntities()
            : base("name=AcademyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademyInfo> AcademyInfo { get; set; }
        public virtual DbSet<Classrooms> Classrooms { get; set; }
        public virtual DbSet<Education_Programs> Education_Programs { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Specialities> Specialities { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
